### ISSUE TITLE
1.4 (stable) plans

### ISSUE THREAD

**Issue by contrarybaton60** [contrarybaton60/Williams-Console#10]
1.4.??? Doesn't WC already have 1.4? [the 1.4 Beta has been out since 4 days ago since at the time of typing this.](https://github.com/contrarybaton60/Williams-Console/releases/tag/v1.4%2Bmc1.21)

changes:
- adds Old Combat Mod or Combatify
- re-adds Legacy Mipmaps
- re-adds Not Enough Animations

other changes:
- idk

**Comment by omo50** [comment]
you should release a full version of 1.4 before just adding a subversion

**Comment by contrarybaton60** [comment]
Yeah, I get ya, the beta is pretty much complete just without the above.

**Comment by contrarybaton60** [comment]
combatify seems to mess up the held item tooltips

**Comment by contrarybaton60** [comment]
https://github.com/contrarybaton60/Williams-Console/releases/tag/v1.4b2%2Bmc1.21

**Comment by contrarybaton60** [comment]
https://github.com/contrarybaton60/Williams-Console/releases/tag/v1.4b3%2Bmc1.21
