### ISSUE TITLE
Legacy console crafting menu isn't working

### ISSUE THREAD

**Issue by tristann21** [contrarybaton60/Williams-Console#7]
When I press the 'E' key on my keyboard or the 'X' button on my controller, the crafting menu fails to appear. Instead, the inventory menu is displayed.

Similarly, the crafting menu from the console versions doesn't show when using a crafting table.
![image](https://github.com/contrarybaton60/Williams-Console/assets/154575581/ba53aa36-dfdf-4eea-a9c4-cf281e38c2f3)

[logs.txt](https://github.com/user-attachments/files/16059723/logs.txt)

**Comment by contrarybaton60** [comment]
This is because the "Classic Crafting" option is enabled (and has been since the first release). you can disable it to get the legacy crafting, but modded items can be difficult to craft, which is why I left the option on.
