### ISSUE TITLE
1.3.4 plans

### ISSUE THREAD

**Issue by contrarybaton60** [contrarybaton60/Williams-Console#9]
Regular stuff
- adds Friends&Foes
- adds World Host
- updates Legacy4J 
- removes The Open Sauce Toast Killer 
- removes SmartBlockPlacement

_Maybe?_ re-add 1.20.4 support, and if so:
- backports changes from 1.3.2 to 1.3.4
- removes Nvidium
- removes Cool Elytra
- adds Sushi Bar

These versions could've been released a week ago, but the 1.7 versions of Legacy4J have been buggy, so I will be holding off updates for now.

Suggestions are welcome.

**Comment by contrarybaton60** [comment]
Another feature:
-adds [Default Dark Mode](https://modrinth.com/resourcepack/default-dark-mode)

**Comment by contrarybaton60** [comment]
> Another feature: -adds [Default Dark Mode](https://modrinth.com/resourcepack/default-dark-mode)

I'm gonna take that back, it will include [arichornloverALT](https://github.com/arichornloverALT/Default-Dark-Mode)'s fork of it, as it contains the Legacy4J assets.

**Comment by contrarybaton60** [comment]
You can modify mines

**Comment by omo50** [comment]
I would not support 1.20.4 again due to it's much smaller size. In terms of priorities you really should focus on 1.21 or 1.20.1. I'd also keep Nvidium as it doesn't suffer from memory leaks on 1.20.6+

**Comment by contrarybaton60** [comment]
> I would not support 1.20.4 again due to it's much smaller size. In terms of priorities you really should focus on 1.21 or 1.20.1. I'd also keep Nvidium as it doesn't suffer from memory leaks on 1.20.6+

I agree with you, It's the reason why I put "_maybe_". having to suppprt a version that is already "moved on" by the community isn't really a smart move.

**Comment by contrarybaton60** [comment]
A beta is now released, there will not be a 1.20.4 version of it.

https://github.com/contrarybaton60/Williams-Console/releases/tag/v1.3.4
